create schema if not exists raw_data;

create table if not exists raw_data.meta_info_match(
	match_id text,
	player_id text,
	started_at text,
	membership text,
	anticheat_required text,
	game_skill_level text,
	team_id text,
	faction text,
	winner_team text
	);
create table if not exists raw_data.life_stats(
	Average_Headshots text,
	Matches text,
	Total_Headshots text,
	Win_Rate text,
	Wins text,
	Longest_Win_Streak text,
	Current_Win_Streak text,
	Average_KD text,
	player_id text,
	elo text,
	faceit_level text,
	time_parse text
);
create table if not exists raw_data.map_stats(
	map_cs text,
	player_id text,
	KD text,
	Average_Quadro_Kills text,
	Average_MVPs text,
	Average_Assists text,
	Penta_Kills text,
	Headshots text,
	Average_Kills text,
	Quadro_Kills text,
	Wins text,
	Win_Rate text,
	Matches text,
	Triple_Kills text,
	Headshots_per_Match text,
	Average_KR text,
	Average_Deaths text,
	Total_Headshots text,
	KR text,
	Average_Triple_Kills text,
	Average_Headshots text,
	Rounds text,
	Assists text,
	MVPs text,
	Kills text,
	Deaths text,
	Average_Penta_Kills text,
	Average_KD text,
	time_parse text
);
create table if not exists raw_data.players_previous_stats(
	match_id text,
	player_id text,
	Score text,
	Overtime_score text,
	First_Half_Score text,
	Second_Half_Score text,
	Final_Score text,
	map_csgo text,
	Deaths text,
	Headshots_per text,
	Headshots text, 
	Kills text,
	KD text,
	Penta_Kills text,
	Quadro_Kills text,
	Triple_Kills text,
	MVPs text,
	KR text,
	Assists text,
	result_match text
)